version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/deploy

permissions:
  - object: /
    pattern: "*.sh"
    mode: 755

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
