spring:
  application:
    name: docswant
  profiles:
    active: local

server:
  port: 8080

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/docswant?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: docswant
    password: docswant
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

jwt:
  secret: ZG9jc3dhbnRsb2NhbHNlY3JldGRvY3N3YW50bG9jYWwK
  access-token-expired-time: 3600
  refresh-token-expired-time: 2592000

---
spring:
  config:
    activate:
      on-profile: dev
    import: 'aws-parameterstore:'
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expired-time: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
  refresh-token-expired-time: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}

logging:
  level: debug
